name       : playerctl
version    : 2.3.1
release    : 7
source     :
    - https://github.com/altdesktop/playerctl/releases/download/v2.3.1/playerctl-2.3.1.tar.xz : 36fbd2d168e1ba94d538022f358dc08818b90a4e8ea7eb4150eaaa8837630ed9
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : mpris command-line controller and library for spotify, vlc, audacious, bmp, xmms2, and others.
description: |
    Playerctl is a command-line utility and library for controlling media players that implement the MPRIS D-Bus Interface Specification. Playerctl makes it easy to bind player actions, such as play and pause, to media keys.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - gtk-doc
setup      : |
    %meson_configure -Dbash-completions=true -Dzsh-completions=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/*.a
