name       : playerctl
version    : 0.6.0
release    : 2
source     :
    - https://github.com/acrisci/playerctl/archive/v0.6.0.tar.gz : c7af7291fa3efad07dabae62ad31f366e8730a84439e2499c6fb6b09f4a7d0e7
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : mpris command-line controller and library for spotify, vlc, audacious, bmp, xmms2, and others.
description: |
    Playerctl is a command-line utility and library for controlling media players that implement the MPRIS D-Bus Interface Specification. Playerctl makes it easy to bind player actions, such as play and pause, to media keys.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - gtk-doc
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
