name       : playerctl
version    : 2.0.1
release    : 3
source     :
    - https://github.com/acrisci/playerctl/releases/download/v2.0.1/playerctl-2.0.1.tar.xz : c3ae6d74ddd951767da4e7852a76a88a2920ed02f126dab6e3b6f0c77549c74f
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : mpris command-line controller and library for spotify, vlc, audacious, bmp, xmms2, and others.
description: |
    Playerctl is a command-line utility and library for controlling media players that implement the MPRIS D-Bus Interface Specification. Playerctl makes it easy to bind player actions, such as play and pause, to media keys.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - gtk-doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/*.a
