name       : playerctl
version    : 0.5.0
release    : 1
source     :
    - https://github.com/acrisci/playerctl/archive/v0.5.0.tar.gz : e1ea761c05774471a0a1274ad93805178b32d55d358ece0424fd087c1def8017
license    : GPL-3.0
component  : multimedia.audio
summary    : mpris command-line controller and library for spotify, vlc, audacious, bmp, xmms2, and others.
description: |
    mpris command-line controller and library for spotify, vlc, audacious, bmp, xmms2, and others.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - gtk-doc
setup      : |
    %autogen --disable-static
build      : |
    %make -j1
install    : |
    %make_install
