name       : playerctl
version    : 2.2.1
release    : 6
source     :
    - https://github.com/altdesktop/playerctl/releases/download/v2.2.1/playerctl-2.2.1.tar.xz : 38dc1889d31ae3cb11640f9d0f6779df9025eb90e577112c024a6588c3bfdbf9
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : mpris command-line controller and library for spotify, vlc, audacious, bmp, xmms2, and others.
description: |
    Playerctl is a command-line utility and library for controlling media players that implement the MPRIS D-Bus Interface Specification. Playerctl makes it easy to bind player actions, such as play and pause, to media keys.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - gtk-doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/*.a
